// <auto-generated />
namespace LinaMovies.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SeedYouTube : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeedYouTube));
        
        string IMigrationMetadata.Id
        {
            get { return "201804080748573_SeedYouTube"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
